// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_k1n_I7737Zt0IaxDENn-YCAY4Y2gbXg',
    appId: '1:975839578749:web:d0146356420b56cb14bf14',
    messagingSenderId: '975839578749',
    projectId: 'helpinghand-26655',
    authDomain: 'helpinghand-26655.firebaseapp.com',
    storageBucket: 'helpinghand-26655.appspot.com',
    measurementId: 'G-SSRF6WYET4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhvCZnx5P93FrpNeDt0IKjXINqAkbAVnY',
    appId: '1:975839578749:android:32ba528b606756ee14bf14',
    messagingSenderId: '975839578749',
    projectId: 'helpinghand-26655',
    storageBucket: 'helpinghand-26655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX3nfcznshkTMCOeO2zHhWOh33mGQf6uE',
    appId: '1:975839578749:ios:4d351bcc1d042e3f14bf14',
    messagingSenderId: '975839578749',
    projectId: 'helpinghand-26655',
    storageBucket: 'helpinghand-26655.appspot.com',
    iosClientId: '975839578749-58pf3j4scmj4jp94129ejd94ekqm0l5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpingHand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX3nfcznshkTMCOeO2zHhWOh33mGQf6uE',
    appId: '1:975839578749:ios:be66e0d57d755d3d14bf14',
    messagingSenderId: '975839578749',
    projectId: 'helpinghand-26655',
    storageBucket: 'helpinghand-26655.appspot.com',
    iosClientId: '975839578749-jj6pl6c52fsbqq27r1el1og9fn8qboer.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpingHand.RunnerTests',
  );
}
